### ISSUE TITLE
Can not start porcupine trigger - no connection to AlexaPi

### ISSUE THREAD

**Issue by rchobby-net** [shivasiddharth/avs-device-sdk-pi#3] opened 2022-02-23 19:28 UTC
I tried the following script:
`python3 /home/pi/avs-device-sdk-pi/Alexa/alexa_picovoice_trigger.py --access_key 9EEydeESEgnvO/OhArD9yZ8trm7k+o770CXwLEE9orxxxxxx== --keyword_paths /home/pi/alexa_rasperry-pi.ppn`

And I get the following answer:

> Traceback (most recent call last):
> File "/home/pi/avs-device-sdk-pi/Alexa/alexa_picovoice_trigger.py", line 218, in <module>
> main()
>  File "/home/pi/avs-device-sdk-pi/Alexa/alexa_picovoice_trigger.py", line 214, in main
>  input_device_index=args.audio_device_index).run()
>  File "/home/pi/avs-device-sdk-pi/Alexa/alexa_picovoice_trigger.py", line 73, in run
>  s.connect(('localhost', SOCKET_PORT))
>  ConnectionRefusedError: [Errno 111] Connection refused
> 

AlexPi works with "T"-command.
How can I solve the problem?

**Comment by shivasiddharth** [comment] 2022-02-24 02:07
That's a script for my own development. Please do not use that. Duplicate of #2  Is some external source directing you to that script or are you guys trying it out on your own ?

**Comment by rchobby-net** [comment] 2022-02-24 07:59
Thank you for the fast replay. I don't understand what you exactly mean. I followed these instructions:
[https://github.com/shivasiddharth/avs-device-sdk-pi](https://github.com/shivasiddharth/avs-device-sdk-pi) and this video [https://www.youtube.com/watch?v=uYtlX260JOc&t=439s](https://www.youtube.com/watch?v=uYtlX260JOc&t=439s). If there an other link, please tell me that. 
Thank you

**Comment by shivasiddharth** [comment] 2022-02-24 08:20
The YouTube is re-directing to a wrong branch of the Git. I have fixed the link in YouTube. This is what you need to follow: https://github.com/shivasiddharth/avs-device-sdk-pi

**Comment by shivasiddharth** [comment] 2022-02-24 08:20
Use this file: https://github.com/shivasiddharth/avs-device-sdk-pi/blob/scripts/alexa_picovoice_trigger.py

**Comment by rchobby-net** [comment] 2022-02-24 08:27
Can I also use this installation process [https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/raspberry-pi-script.html](https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/raspberry-pi-script.html) from the "script". That I have used in the moment.

Thank you

**Comment by rchobby-net** [comment] 2022-02-24 15:48
I have now the SDk new installed and you hints take into consideration.
"alexa_picovoice_trigger.py" and "alexa_raspberry-pi.ppn" are in /home/pi/.

my scrip looks like that:
`pi@raspberrypi:~ $ python3 /home/pi/alexa_picovoice_trigger.py --access_key 9EEydeESEgnvO/OhArD9yZ8trm7k+o770CXwLEE9orKHhjudk....== --keyword_paths /home/pi/alexa_rasperry-pi.ppn
`
Now I get this message:
`pi@raspberrypi:~ $ python3 /home/pi/alexa_picovoice_trigger.py --access_key 9EEydeESEgnvO/OhArD9yZ8trm7k+o770CXwLEE9orKHhjudk0....== --keyword_paths /home/pi/alexa_rasperry-pi.ppn
Traceback (most recent call last):
  File "/home/pi/alexa_picovoice_trigger.py", line 210, in <module>
    main()
  File "/home/pi/alexa_picovoice_trigger.py", line 206, in main
    input_device_index=args.audio_device_index).run()
  File "/home/pi/alexa_picovoice_trigger.py", line 89, in run
    sensitivities=self._sensitivities)
  File "/home/pi/.local/lib/python3.7/site-packages/pvporcupine/__init__.py", line 82, in create
    sensitivities=sensitivities)
  File "/home/pi/.local/lib/python3.7/site-packages/pvporcupine/porcupine.py", line 132, in __init__
    raise IOError("Couldn't find keyword file at '%s'." % x)
OSError: Couldn't find keyword file at '/home/pi/alexa_rasperry-pi.ppn'.
`
I must do something wrong, but what?

**Comment by shivasiddharth** [comment] 2022-02-24 16:28
Looks like you do not have the keyword file at the given destination "/home/pi/alexa_rasperry-pi.ppn"

**Comment by rchobby-net** [comment] 2022-02-24 16:56
Yes, it they are there.
`pi@raspberrypi:~ $ cd /home/pi/
pi@raspberrypi:~ $ dir
alexa_picovoice_trigger.py  Desktop    Music	 sdk-folder  Videos
alexa_raspberry-pi.ppn	    Documents  Pictures  Templates
Bookshelf		    Downloads  Public	 test.wav
pi@raspberrypi:~ $ 
`

**Comment by shivasiddharth** [comment] 2022-02-24 17:29
> pi@raspberrypi:~ $ python3 /home/pi/alexa_picovoice_trigger.py --access_key 9EEydeESEgnvO/OhArD9yZ8trm7k+o770CXwLEE9orKHhjudk....== --keyword_paths /home/pi/alexa_rasperry-pi.ppn

Please look at the spelling you have used. You have used "/home/pi/alexa_rasperry-pi.ppn" "b" is missing.

**Closed as completed by shivasiddharth** 2022-02-24 17:29 UTC

**Comment by rchobby-net** [comment] 2022-02-24 17:42
Thank you for your patience, this was it.

**Comment by rchobby-net** [comment] 2022-02-24 19:08
Your program is working. I see the
`Listening {
  alexa (0.50)
}

But "Alexa" won't activate. I only get a "t" on the screen:
`Listening {
  alexa (0.50)
}
[2022-02-24 20:03:52.485612] Detected alexa
t

`

**Comment by shivasiddharth** [comment] 2022-02-24 22:29
Please read through the instructions properly. You need to change the window id in the file.

**Comment by rchobby-net** [comment] 2022-02-25 10:20
Now everything works. Thank you for your patience with my questions.
